name = "wazoo-api"
main = "src/index.ts"
compatibility_date = "2026-07-13"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.wazoo.dev", custom_domain = true }
]

[vars]
API_BASE_URL = "https://api.wazoo.dev"
TURSO_DATABASE_URL = ""
TURSO_ORGANIZATION_SLUG = ""
TURSO_GROUP = "default"
WAZOO_ENV = "prod"
STRIPE_PRICE_ID = ""

[observability]
enabled = true
head_sampling_rate = 1
